print (" ------------------------------------------------")
print ("|                                               |")
print ("|    01HelloWorld                               |")
print ("|    Name : Vicky                               |")
print ("|    Version : 01                               |")
print ("|                                               |")
print (" ------------------------------------------------")
print ("Hello World")