print (" ------------------------------------------------")
print ("|                                               |")
print ("|    01Hello World                              |")
print ("|    Name : Vicky                               |")
print ("|    Version : 01                               |")
print ("|                                               |")
print (" ------------------------------------------------")
