print (" ------------------------------------------------")
print ("|                                               |")
print ("|    01GoodbyeWorld                             |")
print ("|    Name : Vicky                               |")
print ("|    Version : 01                               |")
print ("|                                               |")
print (" ------------------------------------------------")
print("Hello World")
enter = input("------> Program paused - press enter to continue")
print("Goodbye World")