print (" ------------------------------------------------")
print ("|                                               |")
print ("|    02GoodbyePerson                            |")
print ("|    Name : Vicky                               |")
print ("|    Version : 01                               |")
print ("|                                               |")
print (" ------------------------------------------------")
print ("Hello")
x = input("What is your name ? ")
print("Goodbye " + x)